import {
  Image,
  File,
  Video,
  Music,
  ChevronLeft,
  Settings,
  Ellipsis,
  X,
  FolderPlus,
  Delete,
  Folder,
  ChevronRight,
  Download,
  Activity,
  Wifi,
  Plus,
  RotateCcw,
  Trash,
  Check,
  RefreshCcw,
  KeyRound,
  Eye,
  FileArchive,
  Home,
  User,
  MonitorSpeaker,
  TriangleAlert,
  Settings2,
  Bot,
  Globe,
  Sparkles,
  Info,
  EyeOff,
  Thermometer,
  ListCollapse,
  FolderPen,
  Sun,
  Moon,
  Archive,
  ShieldCheck,
  MessageCircleMore,
  Star,
  BellRing,
  ArrowRight,
  Handshake,
  Pen,
  CloudAlert,
  Search
} from "lucide-react-native";
import { iconWithClassName } from "./iconWithClassName";

iconWithClassName(File);
iconWithClassName(Video);
iconWithClassName(Music);
iconWithClassName(Image);
iconWithClassName(ChevronLeft);
iconWithClassName(Settings);
iconWithClassName(Ellipsis);
iconWithClassName(X);
iconWithClassName(FolderPlus);
iconWithClassName(Delete);
iconWithClassName(Folder);
iconWithClassName(ChevronRight);
iconWithClassName(Download);
iconWithClassName(Activity);
iconWithClassName(Wifi);
iconWithClassName(Plus);
iconWithClassName(RotateCcw);
iconWithClassName(Trash);
iconWithClassName(Check);
iconWithClassName(RefreshCcw);
iconWithClassName(KeyRound);
iconWithClassName(Eye);
iconWithClassName(FileArchive);
iconWithClassName(Home);
iconWithClassName(User);
iconWithClassName(MonitorSpeaker);
iconWithClassName(TriangleAlert);
iconWithClassName(Settings2);
iconWithClassName(Bot);
iconWithClassName(Globe);
iconWithClassName(Sparkles);
iconWithClassName(Info);
iconWithClassName(EyeOff);
iconWithClassName(Thermometer);
iconWithClassName(ListCollapse);
iconWithClassName(FolderPen);
iconWithClassName(Sun);
iconWithClassName(Moon);
iconWithClassName(Archive);
iconWithClassName(ShieldCheck);
iconWithClassName(MessageCircleMore);
iconWithClassName(Star);
iconWithClassName(BellRing);
iconWithClassName(ArrowRight);
iconWithClassName(Handshake);
iconWithClassName(Pen);
iconWithClassName(CloudAlert);
iconWithClassName(Search);

export {
  Image,
  File,
  Video,
  Music,
  ChevronLeft,
  Settings,
  Ellipsis,
  X,
  FolderPlus,
  Delete,
  Folder,
  ChevronRight,
  Download,
  Activity,
  Wifi,
  Plus,
  RotateCcw,
  Trash,
  Check,
  RefreshCcw,
  KeyRound,
  Eye,
  FileArchive,
  Home,
  User,
  MonitorSpeaker,
  TriangleAlert,
  Settings2,
  Bot,
  Globe,
  Sparkles,
  Info,
  EyeOff,
  Thermometer,
  ListCollapse,
  FolderPen,
  Sun,
  Moon,
  Archive,
  ShieldCheck,
  MessageCircleMore,
  Star,
  BellRing,
  ArrowRight,
  Handshake,
  Pen,
  CloudAlert,
  Search
};
